server:
  port: 91

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          default_batch_fetch_size: 1000 # jpa가 유연한 쿼리를 날릴 수 있도록 함 (1+N -> 1+1) (in 쿼리로 변경)
#          show_sql: true
          format_sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
